using SarifHub.Domain.Common;

namespace SarifHub.Infrastructure.Seeding;

/// <summary>
/// Rule packs for the development seed — the same content as the frontend mock (<c>frontend/src/api/mock/rulePacks.ts</c>).
/// CodeQL entries use real, public CodeQL query ids. The Semgrep entries use a <c>demo.</c> prefix: they are an invented
/// rule pack, not rules from the Semgrep registry. Phase 4 replaces seeded history with generated SARIF fixtures.
/// </summary>
internal static class DemoRulePacks
{
    /// <summary>An ASP.NET Core payments service.</summary>
    public static IReadOnlyList<RuleTemplate> Dotnet { get; } =
    [
        new(
            "CodeQL",
            "cs/sql-injection",
            "SQL query built from user-controlled sources",
            Severity.Critical,
            ["CWE-89"],
            "Building a SQL query from user-controlled input without parameters lets an attacker change the query.",
            "This query depends on a user-provided value from the request route.",
            ["src/Payments.Api/Repositories/RefundRepository.cs", "src/Payments.Api/Repositories/LedgerRepository.cs"],
            "    var sql = \"SELECT * FROM refunds WHERE id = '\" + refundId + \"'\";"),
        new(
            "CodeQL",
            "cs/path-injection",
            "Uncontrolled data used in path expression",
            Severity.High,
            ["CWE-22", "CWE-73"],
            "Using request data to build a file path can let an attacker read or write files outside the intended folder.",
            "This path depends on a user-provided value.",
            ["src/Payments.Api/Controllers/StatementsController.cs", "src/Payments.Api/Services/ExportService.cs"],
            "    var fullPath = Path.Combine(_options.ExportRoot, fileName);"),
        new(
            "CodeQL",
            "cs/hardcoded-credentials",
            "Hard-coded credentials",
            Severity.Critical,
            ["CWE-798"],
            "Credentials in source code are exposed to anyone with repository access and cannot be rotated safely.",
            "The hard-coded value \"sk_live_…\" flows to a credential parameter.",
            ["src/Payments.Api/Integrations/AcquirerClient.cs"],
            "    _http.DefaultRequestHeaders.Add(\"X-Api-Key\", \"sk_live_<redacted>\");"),
        new(
            "CodeQL",
            "cs/log-forging",
            "Log entries created from user input",
            Severity.Medium,
            ["CWE-117"],
            "Writing unsanitized user input to logs lets an attacker forge log entries.",
            "This log entry depends on a user-provided value.",
            ["src/Payments.Api/Controllers/RefundsController.cs", "src/Payments.Api/Controllers/WebhooksController.cs", "src/Payments.Api/Middleware/RequestLoggingMiddleware.cs"],
            "    _logger.LogInformation(\"Refund requested for order \" + request.OrderId);"),
        new(
            "CodeQL",
            "cs/insecure-randomness",
            "Insecure randomness",
            Severity.High,
            ["CWE-338"],
            "System.Random is predictable and must not be used for security-sensitive values.",
            "A value from System.Random is used to generate a security token.",
            ["src/Payments.Api/Services/IdempotencyKeyService.cs", "src/Payments.Api/Services/OtpService.cs"],
            "    new Random().NextBytes(bytes);"),
        new(
            "CodeQL",
            "cs/cleartext-storage-of-sensitive-information",
            "Clear text storage of sensitive information",
            Severity.Medium,
            ["CWE-312"],
            "Sensitive data is written to storage without encryption.",
            "The card holder name is stored in clear text.",
            ["src/Payments.Api/Repositories/CustomerRepository.cs"],
            "    \"INSERT INTO customers (id, card_holder, email) VALUES (@Id, @CardHolder, @Email)\","),
        new(
            "Semgrep",
            "demo.csharp.jwt.lifetime-validation-disabled",
            "JWT lifetime validation disabled",
            Severity.Critical,
            ["CWE-613"],
            "Disabling lifetime validation accepts expired tokens forever.",
            "TokenValidationParameters.ValidateLifetime is set to false.",
            ["src/Payments.Api/Program.cs"],
            "    ValidateLifetime = false,"),
        new(
            "Semgrep",
            "demo.csharp.cors.allow-any-origin-with-credentials",
            "CORS allows any origin with credentials",
            Severity.High,
            ["CWE-942"],
            "Allowing any origin together with credentials lets any website make authenticated requests.",
            "SetIsOriginAllowed(_ => true) is combined with AllowCredentials().",
            ["src/Payments.Api/Program.cs"],
            "    .SetIsOriginAllowed(_ => true)"),
        new(
            "Semgrep",
            "demo.csharp.crypto.weak-hash-md5",
            "Weak hash algorithm (MD5)",
            Severity.Medium,
            ["CWE-328"],
            "MD5 is broken for security purposes; use SHA-256 or a password hashing function.",
            "MD5.Create() is used to hash a value.",
            ["src/Payments.Api/Services/WebhookSignatureService.cs", "src/Payments.Api/Services/ReceiptService.cs"],
            "    using var md5 = MD5.Create();"),
        new(
            "Semgrep",
            "demo.csharp.aspnet.missing-authorize",
            "Controller action without authorization",
            Severity.High,
            ["CWE-862"],
            "State-changing actions should require an authenticated, authorized caller.",
            "POST action has no [Authorize] attribute and the controller allows anonymous access.",
            ["src/Payments.Api/Controllers/AdminController.cs", "src/Payments.Api/Controllers/PayoutsController.cs"],
            "    [HttpPost(\"{id}/release\")]"),
        new(
            "Semgrep",
            "demo.csharp.errors.exception-details-in-response",
            "Exception details returned to the client",
            Severity.Low,
            ["CWE-209"],
            "Returning exception messages or stack traces leaks implementation details.",
            "ex.ToString() is returned in the HTTP response body.",
            ["src/Payments.Api/Controllers/RefundsController.cs", "src/Payments.Api/Controllers/StatementsController.cs", "src/Payments.Api/Controllers/WebhooksController.cs"],
            "    return StatusCode(500, ex.ToString());"),
        new(
            "Semgrep",
            "demo.csharp.http.missing-timeout",
            "HttpClient without timeout",
            Severity.Low,
            ["CWE-400"],
            "Calls without a timeout can exhaust threads when a dependency hangs.",
            "HttpClient is created with Timeout = InfiniteTimeSpan.",
            ["src/Payments.Api/Integrations/AcquirerClient.cs", "src/Payments.Api/Integrations/FxRatesClient.cs"],
            "    c.Timeout = Timeout.InfiniteTimeSpan;"),
    ];

    /// <summary>A React frontend with a Node.js server.</summary>
    public static IReadOnlyList<RuleTemplate> TypeScript { get; } =
    [
        new(
            "CodeQL",
            "js/xss",
            "Client-side cross-site scripting",
            Severity.High,
            ["CWE-79"],
            "Writing user-controlled data to the DOM as HTML allows script injection.",
            "Cross-site scripting vulnerability due to a user-provided value.",
            ["src/features/profile/ProfileBio.tsx", "src/features/support/TicketMessage.tsx"],
            "      dangerouslySetInnerHTML={{ __html: message.body }} />"),
        new(
            "CodeQL",
            "js/path-injection",
            "Uncontrolled data used in path expression",
            Severity.High,
            ["CWE-22"],
            "Using request data to build a file path can expose files outside the intended folder.",
            "This path depends on a user-provided value.",
            ["server/routes/tiles.ts", "server/routes/uploads.ts"],
            "  const file = path.join(TILE_ROOT, z, x, `${y}.png`);"),
        new(
            "CodeQL",
            "js/insecure-randomness",
            "Insecure randomness",
            Severity.Medium,
            ["CWE-338"],
            "Math.random() is predictable and must not be used for security-sensitive values.",
            "A value from Math.random() is used as a session identifier.",
            ["src/lib/session.ts"],
            "  return Math.random().toString(36).slice(2);"),
        new(
            "CodeQL",
            "js/clear-text-logging",
            "Clear-text logging of sensitive information",
            Severity.Medium,
            ["CWE-312", "CWE-532"],
            "Logging sensitive values exposes them to anyone with log access.",
            "This logs the access token in clear text.",
            ["src/lib/apiClient.ts", "server/middleware/auth.ts"],
            "  console.debug('Using token', token);"),
        new(
            "CodeQL",
            "js/regex-injection",
            "Regular expression injection",
            Severity.Medium,
            ["CWE-730", "CWE-400"],
            "Building a regular expression from user input can cause catastrophic backtracking.",
            "This regular expression is constructed from a user-provided value.",
            ["server/routes/search.ts"],
            "  const pattern = new RegExp(String(req.query.q), 'i');"),
        new(
            "Semgrep",
            "demo.ts.storage.token-in-localstorage",
            "Access token stored in localStorage",
            Severity.Medium,
            ["CWE-922"],
            "Tokens in localStorage are readable by any script running on the page.",
            "localStorage.setItem('access_token', …) stores a bearer token.",
            ["src/features/auth/useLogin.ts"],
            "localStorage.setItem('access_token', accessToken);"),
        new(
            "Semgrep",
            "demo.ts.react.unsafe-target-blank",
            "Link opens new tab without rel=\"noopener\"",
            Severity.Low,
            ["CWE-1022"],
            "target=\"_blank\" without rel=\"noopener\" lets the opened page control window.opener.",
            "Anchor with target=\"_blank\" has no rel attribute.",
            ["src/components/Footer.tsx", "src/features/help/HelpLinks.tsx", "src/features/billing/InvoiceRow.tsx"],
            "<a href={invoice.pdfUrl} target=\"_blank\">"),
        new(
            "Semgrep",
            "demo.ts.express.missing-helmet",
            "Express app without security headers",
            Severity.Low,
            ["CWE-693"],
            "Security headers such as Content-Security-Policy are not set.",
            "express() app is created without helmet() or equivalent headers.",
            ["server/app.ts"],
            "const app = express();"),
        new(
            "Semgrep",
            "demo.ts.express.cors-wildcard",
            "CORS allows any origin",
            Severity.Medium,
            ["CWE-942"],
            "A wildcard origin lets any website call this API from a browser.",
            "cors({ origin: '*' }) is used on an authenticated router.",
            ["server/app.ts"],
            "app.use(cors({ origin: '*' }));"),
    ];

}
