// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SarifHub.Infrastructure.Persistence;

#nullable disable

namespace SarifHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SarifHubDbContext))]
    partial class SarifHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SarifHub.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("data")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("TargetId")
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_actor_time");

                    b.HasIndex("ProjectId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_project_time");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_actor_type", "actor_type IN ('User', 'ApiKey', 'System', 'Anonymous')");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Findings.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedRiskExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_risk_expires_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Guid>("FirstSeenScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_seen_scan_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("LastSeenScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_seen_scan_id");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lifecycle");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<short>("SeverityRank")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasColumnName("severity_rank")
                        .HasComputedColumnSql("CASE severity WHEN 'Critical' THEN 4 WHEN 'High' THEN 3 WHEN 'Medium' THEN 2 ELSE 1 END", true);

                    b.Property<int?>("StartLine")
                        .HasColumnType("integer")
                        .HasColumnName("start_line");

                    b.Property<string>("TriageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Untriaged")
                        .HasColumnName("triage_status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("AcceptedRiskExpiresAt")
                        .HasDatabaseName("ix_findings_risk_expiry")
                        .HasFilter("triage_status = 'AcceptedRisk'");

                    b.HasIndex("FilePath")
                        .HasDatabaseName("ix_findings_file_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FilePath"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FilePath"), new[] { "gin_trgm_ops" });

                    b.HasIndex("FirstSeenScanId")
                        .HasDatabaseName("ix_findings_first_seen_scan_id");

                    b.HasIndex("LastSeenScanId")
                        .HasDatabaseName("ix_findings_last_seen_scan_id");

                    b.HasIndex("Message")
                        .HasDatabaseName("ix_findings_message_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Message"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Message"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_findings_rule");

                    b.HasIndex("ProjectId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_findings_project_id_fingerprint");

                    b.HasIndex("ProjectId", "LastSeenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_findings_project_last_seen");

                    b.HasIndex("ProjectId", "SeverityRank", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_findings_open_severity")
                        .HasFilter("lifecycle <> 'Resolved'");

                    b.ToTable("findings", null, t =>
                        {
                            t.HasCheckConstraint("ck_findings_accepted_risk_expiry", "(triage_status = 'AcceptedRisk') = (accepted_risk_expires_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_findings_lifecycle", "lifecycle IN ('New', 'Existing', 'Reopened', 'Resolved')");

                            t.HasCheckConstraint("ck_findings_severity", "severity IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_findings_start_line_positive", "start_line > 0");

                            t.HasCheckConstraint("ck_findings_triage_status", "triage_status IN ('Untriaged', 'Confirmed', 'FalsePositive', 'AcceptedRisk')");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Findings.FindingOccurrence", b =>
                {
                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change");

                    b.Property<int?>("EndLine")
                        .HasColumnType("integer")
                        .HasColumnName("end_line");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PartialFingerprints")
                        .HasColumnType("jsonb")
                        .HasColumnName("partial_fingerprints");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Snippet")
                        .HasColumnType("text")
                        .HasColumnName("snippet");

                    b.Property<int?>("StartColumn")
                        .HasColumnType("integer")
                        .HasColumnName("start_column");

                    b.Property<int?>("StartLine")
                        .HasColumnType("integer")
                        .HasColumnName("start_line");

                    b.HasKey("ScanId", "FindingId")
                        .HasName("pk_finding_occurrences");

                    b.HasIndex("FindingId", "ScanId")
                        .HasDatabaseName("ix_occurrences_finding");

                    b.ToTable("finding_occurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_finding_occurrences_change", "change IN ('New', 'Existing', 'Reopened')");

                            t.HasCheckConstraint("ck_finding_occurrences_severity", "severity IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_finding_occurrences_start_column_positive", "start_column > 0");

                            t.HasCheckConstraint("ck_finding_occurrences_start_line_positive", "start_line > 0");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Findings.FindingResolution", b =>
                {
                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.HasKey("ScanId", "FindingId")
                        .HasName("pk_finding_resolutions");

                    b.HasIndex("FindingId")
                        .HasDatabaseName("ix_resolutions_finding");

                    b.ToTable("finding_resolutions", (string)null);
                });

            modelBuilder.Entity("SarifHub.Domain.Projects.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("character(8)")
                        .HasColumnName("prefix");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("_keyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.PrimitiveCollection<string[]>("_scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_api_keys_created_by_id");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_prefix");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_project_id_name");

                    b.ToTable("api_keys", null, t =>
                        {
                            t.HasCheckConstraint("ck_api_keys_key_hash_sha256", "octet_length(key_hash) = 32");

                            t.HasCheckConstraint("ck_api_keys_name_length", "length(name) BETWEEN 1 AND 60");

                            t.HasCheckConstraint("ck_api_keys_scopes", "scopes <@ ARRAY['scans:write', 'gate:read']::text[] AND cardinality(scopes) > 0");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("main")
                        .HasColumnName("default_branch");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("LastScanNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_scan_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("text")
                        .HasColumnName("repository_url");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GatePolicy", "SarifHub.Domain.Projects.Project.GatePolicy#GatePolicy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("MaxCritical")
                                .HasColumnType("integer")
                                .HasColumnName("gate_max_critical");

                            b1.Property<int?>("MaxHigh")
                                .HasColumnType("integer")
                                .HasColumnName("gate_max_high");

                            b1.Property<int?>("MaxMedium")
                                .HasColumnType("integer")
                                .HasColumnName("gate_max_medium");
                        });

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_projects_created_by_id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_key");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_gate_max_critical", "gate_max_critical >= 0");

                            t.HasCheckConstraint("ck_projects_gate_max_high", "gate_max_high >= 0");

                            t.HasCheckConstraint("ck_projects_gate_max_medium", "gate_max_medium >= 0");

                            t.HasCheckConstraint("ck_projects_key_format", "key ~ '^[a-z0-9][a-z0-9-]{1,62}$'");

                            t.HasCheckConstraint("ck_projects_name_length", "length(name) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("ck_projects_repository_url_https", "repository_url ~ '^https://'");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user");

                    b.ToTable("project_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_members_role", "role IN ('Viewer', 'Developer', 'SecurityLead', 'Admin')");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Rules.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HelpUri")
                        .HasColumnType("text")
                        .HasColumnName("help_uri");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.PrimitiveCollection<string[]>("_cwe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("cwe")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.HasKey("Id")
                        .HasName("pk_rules");

                    b.HasIndex("ToolName", "RuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_rules_tool_name_rule_id");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("SarifHub.Domain.Scans.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("branch");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text")
                        .HasColumnName("commit_sha");

                    b.Property<int>("CriticalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("critical_count");

                    b.Property<int>("ExistingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("existing_count");

                    b.Property<string>("GateEvaluation")
                        .HasColumnType("jsonb")
                        .HasColumnName("gate_evaluation");

                    b.Property<string>("GateResult")
                        .HasColumnType("text")
                        .HasColumnName("gate_result");

                    b.Property<int>("HighCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("high_count");

                    b.Property<int>("LowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("low_count");

                    b.Property<int>("MediumCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("medium_count");

                    b.Property<int>("NewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("new_count");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("ReopenedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reopened_count");

                    b.Property<int>("ResolvedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("resolved_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_count");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UploadedByKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_key_id");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<byte[]>("_sarifSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sarif_sha256");

                    b.HasKey("Id")
                        .HasName("pk_scans");

                    b.HasIndex("UploadedByKeyId")
                        .HasDatabaseName("ix_scans_uploaded_by_key_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_scans_uploaded_by_user_id");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_scans_project_id_number");

                    b.HasIndex("ProjectId", "UploadedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_scans_project_uploaded");

                    b.HasIndex("ProjectId", "_sarifSha256")
                        .HasDatabaseName("ix_scans_project_sha");

                    b.ToTable("scans", null, t =>
                        {
                            t.HasCheckConstraint("ck_scans_commit_sha_format", "commit_sha ~ '^[0-9a-f]{7,64}$'");

                            t.HasCheckConstraint("ck_scans_gate_result", "gate_result IN ('Passed', 'Failed')");

                            t.HasCheckConstraint("ck_scans_number_positive", "number > 0");

                            t.HasCheckConstraint("ck_scans_one_uploader", "num_nonnulls(uploaded_by_user_id, uploaded_by_key_id) = 1");

                            t.HasCheckConstraint("ck_scans_status", "status IN ('Completed', 'Rejected')");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Scans.ScanArtifact", b =>
                {
                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<long>("OriginalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("original_bytes");

                    b.Property<byte[]>("_contentGzip")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_gzip");

                    b.HasKey("ScanId")
                        .HasName("pk_scan_artifacts");

                    b.ToTable("scan_artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_scan_artifacts_original_bytes", "original_bytes > 0");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Scans.ScanTool", b =>
                {
                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<string>("ToolName")
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<string>("ToolVersion")
                        .HasColumnType("text")
                        .HasColumnName("tool_version");

                    b.HasKey("ScanId", "ToolName")
                        .HasName("pk_scan_tools");

                    b.ToTable("scan_tools", (string)null);
                });

            modelBuilder.Entity("SarifHub.Domain.Triage.TriageDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_triage_decisions");

                    b.HasIndex("DecidedById")
                        .HasDatabaseName("ix_triage_decisions_decided_by_id");

                    b.HasIndex("FindingId", "DecidedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_triage_finding");

                    b.ToTable("triage_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_triage_decisions_accepted_risk_expiry", "(status = 'AcceptedRisk') = (expires_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_triage_decisions_reason_length", "length(reason) <= 1000");

                            t.HasCheckConstraint("ck_triage_decisions_reason_required", "status = 'Confirmed' OR decided_by_id IS NULL OR length(reason) >= 10");

                            t.HasCheckConstraint("ck_triage_decisions_status", "status IN ('Untriaged', 'Confirmed', 'FalsePositive', 'AcceptedRisk')");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_display_name_length", "length(display_name) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("SarifHub.Domain.Audit.AuditEvent", b =>
                {
                    b.HasOne("SarifHub.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_events_projects_project_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Findings.Finding", b =>
                {
                    b.HasOne("SarifHub.Domain.Scans.Scan", null)
                        .WithMany()
                        .HasForeignKey("FirstSeenScanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_findings_scans_first_seen_scan_id");

                    b.HasOne("SarifHub.Domain.Scans.Scan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_findings_scans_last_seen_scan_id");

                    b.HasOne("SarifHub.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_projects_project_id");

                    b.HasOne("SarifHub.Domain.Rules.Rule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_findings_rules_rule_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Findings.FindingOccurrence", b =>
                {
                    b.HasOne("SarifHub.Domain.Findings.Finding", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_findings_finding_id");

                    b.HasOne("SarifHub.Domain.Scans.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_scans_scan_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Findings.FindingResolution", b =>
                {
                    b.HasOne("SarifHub.Domain.Findings.Finding", null)
                        .WithMany("Resolutions")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_resolutions_findings_finding_id");

                    b.HasOne("SarifHub.Domain.Scans.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_resolutions_scans_scan_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Projects.ApiKey", b =>
                {
                    b.HasOne("SarifHub.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_created_by_id");

                    b.HasOne("SarifHub.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_projects_project_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Projects.Project", b =>
                {
                    b.HasOne("SarifHub.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_created_by_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Projects.ProjectMember", b =>
                {
                    b.HasOne("SarifHub.Domain.Projects.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("SarifHub.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Scans.Scan", b =>
                {
                    b.HasOne("SarifHub.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scans_projects_project_id");

                    b.HasOne("SarifHub.Domain.Projects.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("UploadedByKeyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_scans_api_keys_uploaded_by_key_id");

                    b.HasOne("SarifHub.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_scans_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Scans.ScanArtifact", b =>
                {
                    b.HasOne("SarifHub.Domain.Scans.Scan", null)
                        .WithOne()
                        .HasForeignKey("SarifHub.Domain.Scans.ScanArtifact", "ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_artifacts_scans_scan_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Scans.ScanTool", b =>
                {
                    b.HasOne("SarifHub.Domain.Scans.Scan", null)
                        .WithMany("Tools")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_tools_scans_scan_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Triage.TriageDecision", b =>
                {
                    b.HasOne("SarifHub.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_triage_decisions_users_decided_by_id");

                    b.HasOne("SarifHub.Domain.Findings.Finding", null)
                        .WithMany("TriageHistory")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_triage_decisions_findings_finding_id");
                });

            modelBuilder.Entity("SarifHub.Domain.Findings.Finding", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("Resolutions");

                    b.Navigation("TriageHistory");
                });

            modelBuilder.Entity("SarifHub.Domain.Projects.Project", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SarifHub.Domain.Scans.Scan", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
